FROM astrocrpublic.azurecr.io/runtime:3.2-5

ENV AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False \
    RUBIK_SOLVER_ENABLE_START=true \
    RUBIK_SOLVER_AIRFLOW_API_URL=http://localhost:8080 \
    RUBIK_SOLVER_USERNAME=admin \
    RUBIK_SOLVER_PASSWORD=admin \
    RUBIK_SOLVER_START_KEY=dev
